# Generated by Django 6.0.2 on 2026-02-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.PositiveIntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
